name: Test Python simple

on: [push, pull_request]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du repo
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installer pytest
      run: pip install pytest

    - name: Lancer les tests
      run: pytest
